# Generated by Django 3.2.3 on 2021-06-24 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cat', '0002_alter_cat_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='cat',
            name='count',
            field=models.IntegerField(default=0),
        ),
    ]
