# Generated by Django 3.2.3 on 2021-05-30 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsapp',
            name='catid',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='newsapp',
            name='catname',
            field=models.CharField(default='-', max_length=30),
        ),
        migrations.AddField(
            model_name='newsapp',
            name='show',
            field=models.IntegerField(default=0),
        ),
    ]
