# Generated by Django 3.2.3 on 2021-05-31 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsapp', '0002_auto_20210530_2225'),
    ]

    operations = [
        migrations.RenameField(
            model_name='newsapp',
            old_name='pic',
            new_name='picname',
        ),
        migrations.AddField(
            model_name='newsapp',
            name='picurl',
            field=models.TextField(default='-'),
        ),
    ]
