# Generated by Django 3.2.3 on 2021-06-06 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsapp', '0003_auto_20210531_2050'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsapp',
            name='time',
            field=models.CharField(default='0', max_length=12),
        ),
    ]
