# Generated by Django 3.2.3 on 2021-07-02 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsapp', '0005_newsapp_ocatid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsapp',
            name='name',
            field=models.CharField(max_length=150),
        ),
    ]
