# Generated by Django 3.2.3 on 2021-07-05 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsapp', '0006_alter_newsapp_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsapp',
            name='tag',
            field=models.TextField(default=''),
        ),
    ]
