# Generated by Django 3.2.3 on 2021-08-10 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsapp', '0007_newsapp_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsapp',
            name='act',
            field=models.IntegerField(default=0),
        ),
    ]
