# Generated by Django 3.2.3 on 2021-08-19 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsapp', '0008_newsapp_act'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsapp',
            name='rand',
            field=models.IntegerField(default=0),
        ),
    ]
