# Generated by Django 3.2.3 on 2021-05-21 23:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20210521_2352'),
    ]

    operations = [
        migrations.RenameField(
            model_name='main',
            old_name='yt',
            new_name='ig',
        ),
    ]
