# Generated by Django 3.2.3 on 2021-09-03 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0005_manager_ip'),
    ]

    operations = [
        migrations.AddField(
            model_name='manager',
            name='country',
            field=models.TextField(default=''),
        ),
    ]
