# Generated by Django 3.2.3 on 2021-07-10 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contactform', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactform',
            name='sub',
            field=models.TextField(default=''),
        ),
    ]
