# Generated by Django 3.2.3 on 2021-07-16 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trending', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trending',
            name='txt',
            field=models.CharField(default='', max_length=200),
        ),
    ]
